#!/usr/bin/env python3
"""Collect machine-checkable findings from trusted AGENTS.md rules."""

from __future__ import annotations

import argparse
import dataclasses
import json
import re
from collections.abc import Callable, Mapping, Sequence
from pathlib import Path, PurePosixPath
from typing import Any

from ai_review_agents import load_instructions

RULE_RE = re.compile(
    r"(?:размер\s+файла|file\s+size).*?"
    r"(?:не\s+более|до|no\s+more\s+than|maximum|max)\s+"
    r"(\d+)(?:\s*[-–—]\s*(\d+))?\s*(?:строк|lines)",
    re.IGNORECASE | re.DOTALL,
)
CONFIG_SUFFIXES = {".json", ".toml", ".yaml", ".yml", ".ini", ".cfg", ".conf", ".xml"}
GENERATED_NAMES = {"package-lock.json", "pnpm-lock.yaml", "yarn.lock", "uv.lock"}
GENERATED_MARKERS = ("generated file", "auto-generated", "autogenerated", "do not edit")
Loader = Callable[..., tuple[tuple[str, str], ...]]


@dataclasses.dataclass(frozen=True)
class FileSizeRule:
    limit: int
    source: str
    configs: bool = False
    alembic: bool = False
    generated: bool = False


def parse_rule(content: str, source: str, previous: FileSizeRule | None = None) -> FileSizeRule | None:
    plain = re.sub(r"[*_`#]", "", content)
    match = RULE_RE.search(plain)
    if match is None:
        return previous
    limit = max(int(value) for value in match.groups() if value)
    context = plain[match.start() : match.end() + 350].lower()
    explicit = "исключ" in context or "except" in context
    inherited = previous or FileSizeRule(limit, source)
    return FileSizeRule(
        limit=limit,
        source=source,
        configs=("конфиг" in context or "config" in context) if explicit else inherited.configs,
        alembic=("alembic" in context) if explicit else inherited.alembic,
        generated=("автогенер" in context or "generated" in context)
        if explicit
        else inherited.generated,
    )


def effective_rule(instructions: Sequence[tuple[str, str]]) -> FileSizeRule | None:
    rule = None
    for source, content in instructions:
        rule = parse_rule(content, source, rule)
    return rule


def is_exempt(path: str, text: str, rule: FileSizeRule) -> bool:
    value = PurePosixPath(path)
    lower = path.lower()
    if rule.configs and (value.suffix.lower() in CONFIG_SUFFIXES or value.name == "Dockerfile"):
        return True
    if rule.alembic and ("alembic" in value.parts or "/migrations/versions/" in f"/{lower}/"):
        return True
    generated_name = value.name in GENERATED_NAMES or ".generated." in lower or lower.endswith("_pb2.py")
    header = "\n".join(text.splitlines()[:12]).lower()
    return rule.generated and (generated_name or any(item in header for item in GENERATED_MARKERS))


def collect_findings(
    base_sha: str,
    scope: Mapping[str, Any],
    cwd: Path,
    loader: Loader | None = None,
) -> list[dict[str, Any]]:
    findings = []
    instruction_loader = loader or load_instructions
    line_map = scope.get("line_map") if isinstance(scope.get("line_map"), Mapping) else {}
    for raw_path in scope.get("reviewable_files", []):
        path = str(raw_path)
        target = cwd / path
        if not target.is_file():
            continue
        rule = effective_rule(instruction_loader(base_sha, [path], cwd=cwd))
        if rule is None:
            continue
        text = target.read_text(encoding="utf-8", errors="replace")
        changed = line_map.get(path, [])
        lines = len(text.splitlines())
        if is_exempt(path, text, rule) or lines <= rule.limit or not changed:
            continue
        findings.append(
            {
                "severity": "major",
                "file": path,
                "line": int(changed[0]),
                "scenario": f"Файл содержит {lines} строк при лимите {rule.limit} из {rule.source}.",
                "impact": "Изменение нарушает обязательное правило размера файла из AGENTS.md.",
                "fix": "Разделите файл на небольшие связные модули без изменения публичных контрактов.",
                "confidence": 1.0,
            }
        )
    return findings


def write_findings(
    base_sha: str,
    scope_path: Path,
    output: Path,
    repo: Path,
    loader: Loader | None = None,
) -> int:
    scope = json.loads(scope_path.read_text(encoding="utf-8"))
    findings = collect_findings(base_sha, scope, repo, loader)
    payload = {"schema_version": 1, "head_sha": scope["head_sha"], "findings": findings}
    output.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"AGENTS.md deterministic findings: {len(findings)}")
    return len(findings)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base", required=True)
    parser.add_argument("--scope", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--repo", type=Path, default=Path.cwd())
    args = parser.parse_args()
    write_findings(args.base, args.scope, args.output, args.repo)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
