#!/usr/bin/env python3
"""Enforce machine-checkable rules from trusted AGENTS.md files."""

from __future__ import annotations

import argparse
import dataclasses
import json
import re
from collections.abc import Callable, Mapping, Sequence
from pathlib import Path, PurePosixPath
from typing import Any

from ai_review_agents import load_instructions

MAX_FINDINGS = 20
RULE_RE = re.compile(
    r"(?:размер\s+файла|file\s+size).*?"
    r"(?:не\s+более|до|no\s+more\s+than|maximum|max)\s+"
    r"(\d+)(?:\s*[-–—]\s*(\d+))?\s*(?:строк|lines)",
    re.IGNORECASE | re.DOTALL,
)
CONFIG_SUFFIXES = {".json", ".toml", ".yaml", ".yml", ".ini", ".cfg", ".conf", ".xml"}
GENERATED_NAMES = {"package-lock.json", "pnpm-lock.yaml", "yarn.lock", "uv.lock"}
GENERATED_MARKERS = ("generated file", "auto-generated", "autogenerated", "do not edit")
Loader = Callable[[str, Sequence[str]], tuple[tuple[str, str], ...]]


@dataclasses.dataclass(frozen=True)
class FileSizeRule:
    limit: int
    source: str
    exclude_configs: bool = False
    exclude_alembic: bool = False
    exclude_generated: bool = False


def parse_rule(content: str, source: str, previous: FileSizeRule | None = None) -> FileSizeRule | None:
    plain = re.sub(r"[*_`#]", "", content)
    match = RULE_RE.search(plain)
    if match is None:
        return previous
    limit = max(int(value) for value in match.groups() if value)
    context = plain[match.start() : match.end() + 350].lower()
    has_exceptions = "исключ" in context or "except" in context
    return FileSizeRule(
        limit=limit,
        source=source,
        exclude_configs=("конфиг" in context or "config" in context)
        if has_exceptions
        else bool(previous and previous.exclude_configs),
        exclude_alembic=("alembic" in context)
        if has_exceptions
        else bool(previous and previous.exclude_alembic),
        exclude_generated=("автогенер" in context or "generated" in context)
        if has_exceptions
        else bool(previous and previous.exclude_generated),
    )


def effective_rule(instructions: Sequence[tuple[str, str]]) -> FileSizeRule | None:
    rule = None
    for source, content in instructions:
        rule = parse_rule(content, source, rule)
    return rule


def is_exempt(path: str, text: str, rule: FileSizeRule) -> bool:
    value = PurePosixPath(path)
    lower = path.lower()
    if rule.exclude_configs and (value.suffix.lower() in CONFIG_SUFFIXES or value.name == "Dockerfile"):
        return True
    if rule.exclude_alembic and ("alembic" in value.parts or "/migrations/versions/" in f"/{lower}/"):
        return True
    generated_name = value.name in GENERATED_NAMES or ".generated." in lower or lower.endswith("_pb2.py")
    generated_header = any(marker in "\n".join(text.splitlines()[:12]).lower() for marker in GENERATED_MARKERS)
    return rule.exclude_generated and (generated_name or generated_header)


def collect_findings(
    base_sha: str,
    scope: Mapping[str, Any],
    cwd: Path,
    loader: Callable[..., tuple[tuple[str, str], ...]] = load_instructions,
) -> list[dict[str, Any]]:
    findings = []
    line_map = scope.get("line_map") if isinstance(scope.get("line_map"), Mapping) else {}
    for raw_path in scope.get("reviewable_files", []):
        path = str(raw_path)
        target = cwd / path
        if not target.is_file():
            continue
        rule = effective_rule(loader(base_sha, [path], cwd=cwd))
        if rule is None:
            continue
        text = target.read_text(encoding="utf-8", errors="replace")
        if is_exempt(path, text, rule):
            continue
        lines = len(text.splitlines())
        changed = line_map.get(path, [])
        if lines <= rule.limit or not changed:
            continue
        findings.append(
            {
                "severity": "major",
                "file": path,
                "line": int(changed[0]),
                "scenario": f"Файл содержит {lines} строк при лимите {rule.limit} из {rule.source}.",
                "impact": "Изменение нарушает обязательное правило размера файла из AGENTS.md и усложняет сопровождение.",
                "fix": "Разделите файл на небольшие связные модули, сохранив публичные контракты и поведение.",
                "confidence": 1.0,
            }
        )
    return findings


def is_size_finding(value: Mapping[str, Any]) -> bool:
    text = " ".join(str(value.get(key, "")) for key in ("scenario", "impact", "fix")).lower()
    return ("строк" in text or "lines" in text) and ("файл" in text or "file" in text)


def merge_result(result: dict[str, Any], deterministic: Sequence[dict[str, Any]]) -> dict[str, Any]:
    if not deterministic:
        return result
    files = {item["file"] for item in deterministic}
    model = [item for item in result.get("findings", []) if not (item.get("file") in files and is_size_finding(item))]
    findings = list(deterministic) + model
    result["findings"] = findings[:MAX_FINDINGS]
    result["status"] = "completed"
    result["reason"] = "agents-rules-enforced"
    result["verdict"] = "changes-required"
    result["reaction"] = "-1"
    result["blocking_count"] = sum(item.get("severity") in {"blocker", "major"} for item in result["findings"])
    result["summary"] = f"Обязательные правила AGENTS.md: {len(deterministic)}; всего замечаний: {len(result['findings'])}."
    return result


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base", required=True)
    parser.add_argument("--scope", type=Path, required=True)
    parser.add_argument("--result", type=Path, required=True)
    parser.add_argument("--repo", type=Path, default=Path.cwd())
    args = parser.parse_args()
    scope = json.loads(args.scope.read_text(encoding="utf-8"))
    result = json.loads(args.result.read_text(encoding="utf-8"))
    merged = merge_result(result, collect_findings(args.base, scope, args.repo))
    args.result.write_text(json.dumps(merged, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
