DEFAULT_PAGE_SIZE = 1000
HARD_LIMIT_WITH_FIELDS = 5000

FRIEND_FIELDS = [
    "id",
    "first_name",
    "last_name",
    "nickname",
    "domain",
    "bdate",
    "sex",
    "status",
    "online",
    "last_seen_time",
    "last_seen_platform",
    "city_id",
    "city_title",
    "country_id",
    "country_title",
    "has_mobile",
    "can_post",
    "can_see_all_posts",
    "can_write_private_message",
    "timezone",
    "photo_50",
    "photo_100",
    "photo_200_orig",
    "photo_id",
    "relation",
    "contacts_mobile_phone",
    "contacts_home_phone",
    "education_university",
    "education_faculty",
    "education_graduation",
    "universities",
]

FRIEND_HEADERS_RU = {
    "id": "ID",
    "first_name": "Имя",
    "last_name": "Фамилия",
    "nickname": "Никнейм",
    "domain": "Домен",
    "bdate": "Дата рождения",
    "sex": "Пол",
    "status": "Статус",
    "online": "Онлайн",
    "last_seen_time": "Был(а) в сети (время)",
    "last_seen_platform": "Был(а) в сети (платформа)",
    "city_id": "ID города",
    "city_title": "Город",
    "country_id": "ID страны",
    "country_title": "Страна",
    "has_mobile": "Есть мобильный",
    "can_post": "Можно писать на стене",
    "can_see_all_posts": "Видит все записи",
    "can_write_private_message": "Можно писать в ЛС",
    "timezone": "Часовой пояс",
    "photo_50": "Фото 50",
    "photo_100": "Фото 100",
    "photo_200_orig": "Фото 200 (оригинал)",
    "photo_id": "ID фото",
    "relation": "Семейное положение",
    "contacts_mobile_phone": "Телефон (мобильный)",
    "contacts_home_phone": "Телефон (домашний)",
    "education_university": "Университет (ID)",
    "education_faculty": "Факультет (ID)",
    "education_graduation": "Год выпуска",
    "universities": "Университеты",
}
