"""add_photo_analyses_table

Revision ID: 7e41fccb26f6
Revises: a7ca1b5f94d3
Create Date: 2026-05-24 20:49:59.618331

"""
<<<<<<< HEAD
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
=======
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
>>>>>>> 59c5b02f74109d896c970438b9ab9949727f89da
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e41fccb26f6'
<<<<<<< HEAD
down_revision: Union[str, None] = 'a7ca1b5f94d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
=======
down_revision: str | None = 'a7ca1b5f94d3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None
>>>>>>> 59c5b02f74109d896c970438b9ab9949727f89da


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_analyses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('author_vk_id', sa.BigInteger(), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=False),
    sa.Column('photo_vk_id', sa.String(length=255), nullable=False),
    sa.Column('analysis_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_suspicious', sa.Boolean(), nullable=False),
    sa.Column('suspicion_level', sa.String(length=32), nullable=False),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_vk_id', 'photo_vk_id', name='uq_photo_analyses_author_photo')
    )
    op.create_index('ix_photo_analyses_analyzed_at', 'photo_analyses', ['analyzed_at'], unique=False)
    op.create_index('ix_photo_analyses_author_vk_id', 'photo_analyses', ['author_vk_id'], unique=False)
    op.create_index('ix_photo_analyses_suspicion_level', 'photo_analyses', ['suspicion_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_photo_analyses_suspicion_level', table_name='photo_analyses')
    op.drop_index('ix_photo_analyses_author_vk_id', table_name='photo_analyses')
    op.drop_index('ix_photo_analyses_analyzed_at', table_name='photo_analyses')
    op.drop_table('photo_analyses')
    # ### end Alembic commands ###
