"""add keywords tables

Revision ID: 8c89edf76b23
Revises: 
Create Date: 2026-05-24 15:31:51.649807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c89edf76b23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_recalculation_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('single_keyword_id', sa.BigInteger(), nullable=True),
    sa.Column('processed', sa.BigInteger(), nullable=False, server_default='0'),
    sa.Column('updated', sa.BigInteger(), nullable=False, server_default='0'),
    sa.Column('created', sa.BigInteger(), nullable=False, server_default='0'),
    sa.Column('deleted', sa.BigInteger(), nullable=False, server_default='0'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('is_phrase', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_word'), 'keywords', ['word'], unique=True)
    op.create_table('keyword_form_exclusions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('keyword_id', sa.BigInteger(), nullable=False),
    sa.Column('form', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword_id', 'form', name='uq_keyword_form_exclusions_keyword_form')
    )
    op.create_index('ix_keyword_form_exclusions_form', 'keyword_form_exclusions', ['form'], unique=False)
    op.create_index('ix_keyword_form_exclusions_keyword_id', 'keyword_form_exclusions', ['keyword_id'], unique=False)
    op.create_table('keyword_forms',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('keyword_id', sa.BigInteger(), nullable=False),
    sa.Column('form', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword_id', 'form', 'source', name='uq_keyword_forms_keyword_form_source')
    )
    op.create_index('ix_keyword_forms_form', 'keyword_forms', ['form'], unique=False)
    op.create_index('ix_keyword_forms_keyword_id', 'keyword_forms', ['keyword_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_keyword_forms_keyword_id', table_name='keyword_forms')
    op.drop_index('ix_keyword_forms_form', table_name='keyword_forms')
    op.drop_table('keyword_forms')
    op.drop_index('ix_keyword_form_exclusions_keyword_id', table_name='keyword_form_exclusions')
    op.drop_index('ix_keyword_form_exclusions_form', table_name='keyword_form_exclusions')
    op.drop_table('keyword_form_exclusions')
    op.drop_index(op.f('ix_keywords_word'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_table('keyword_recalculation_jobs')
    # ### end Alembic commands ###
