"""add_watchlist_tables

Revision ID: a7ca1b5f94d3
Revises: 8c89edf76b23
Create Date: 2026-05-24 16:26:47.698445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7ca1b5f94d3'
down_revision: Union[str, None] = '8c89edf76b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('consumer_name', sa.Text(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consumer_name', 'event_id', name='uq_processed_events_consumer_event')
    )
    op.create_index('ix_processed_events_consumer_event', 'processed_events', ['consumer_name', 'event_id'], unique=False)
    op.create_table('watchlist_settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('track_all_comments', sa.Boolean(), nullable=False),
    sa.Column('poll_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('max_authors', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_authors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('author_vk_id', sa.BigInteger(), nullable=False),
    sa.Column('source_comment_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('found_comments_count', sa.Integer(), nullable=False),
    sa.Column('monitoring_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('monitoring_stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['settings_id'], ['watchlist_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_vk_id', 'settings_id', name='uq_watchlist_authors_author_settings')
    )
    op.create_index('ix_watchlist_authors_settings_id', 'watchlist_authors', ['settings_id'], unique=False)
    op.create_index('ix_watchlist_authors_status', 'watchlist_authors', ['status'], unique=False)
    op.create_table('moderation_comments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('external_key', sa.Text(), nullable=False),
    sa.Column('post_external_key', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author_vk_id', sa.BigInteger(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('matched_keywords', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('watchlist_author_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_author_id'], ['watchlist_authors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_key')
    )
    op.create_index('ix_moderation_comments_date_id', 'moderation_comments', ['date', 'id'], unique=False)
    op.create_index('ix_moderation_comments_is_read', 'moderation_comments', ['is_read'], unique=False)
    op.create_index('ix_moderation_comments_watchlist_author_id', 'moderation_comments', ['watchlist_author_id'], unique=False)
    op.add_column('keyword_recalculation_jobs', sa.Column('single_keyword_id', sa.BigInteger(), nullable=True))
    op.add_column('keyword_recalculation_jobs', sa.Column('processed', sa.BigInteger(), nullable=False))
    op.add_column('keyword_recalculation_jobs', sa.Column('updated', sa.BigInteger(), nullable=False))
    op.add_column('keyword_recalculation_jobs', sa.Column('created', sa.BigInteger(), nullable=False))
    op.add_column('keyword_recalculation_jobs', sa.Column('deleted', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keyword_recalculation_jobs', 'deleted')
    op.drop_column('keyword_recalculation_jobs', 'created')
    op.drop_column('keyword_recalculation_jobs', 'updated')
    op.drop_column('keyword_recalculation_jobs', 'processed')
    op.drop_column('keyword_recalculation_jobs', 'single_keyword_id')
    op.drop_index('ix_moderation_comments_watchlist_author_id', table_name='moderation_comments')
    op.drop_index('ix_moderation_comments_is_read', table_name='moderation_comments')
    op.drop_index('ix_moderation_comments_date_id', table_name='moderation_comments')
    op.drop_table('moderation_comments')
    op.drop_index('ix_watchlist_authors_status', table_name='watchlist_authors')
    op.drop_index('ix_watchlist_authors_settings_id', table_name='watchlist_authors')
    op.drop_table('watchlist_authors')
    op.drop_table('watchlist_settings')
    op.drop_index('ix_processed_events_consumer_event', table_name='processed_events')
    op.drop_table('processed_events')
    # ### end Alembic commands ###
