"""add_watchlist_tables

Revision ID: a7ca1b5f94d3
Revises: 8c89edf76b23
Create Date: 2026-05-24 16:26:47.698445

"""
<<<<<<< HEAD
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7ca1b5f94d3'
down_revision: Union[str, None] = '8c89edf76b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
=======
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a7ca1b5f94d3'
down_revision: str | None = '8c89edf76b23'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None
>>>>>>> 59c5b02f74109d896c970438b9ab9949727f89da


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('track_all_comments', sa.Boolean(), nullable=False),
    sa.Column('poll_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('max_authors', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_authors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('author_vk_id', sa.BigInteger(), nullable=False),
    sa.Column('source_comment_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('found_comments_count', sa.Integer(), nullable=False),
    sa.Column('monitoring_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('monitoring_stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['settings_id'], ['watchlist_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_vk_id', 'settings_id', name='uq_watchlist_authors_author_settings')
    )
    op.create_index('ix_watchlist_authors_settings_id', 'watchlist_authors', ['settings_id'], unique=False)
    op.create_index('ix_watchlist_authors_status', 'watchlist_authors', ['status'], unique=False)
    
    # Add watchlist_author_id to moderation_comments
    op.add_column('moderation_comments', sa.Column('watchlist_author_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        'fk_moderation_comments_watchlist_author_id',
        'moderation_comments', 'watchlist_authors',
        ['watchlist_author_id'], ['id'],
        ondelete='SET NULL'
    )
    op.create_index('ix_moderation_comments_watchlist_author_id', 'moderation_comments', ['watchlist_author_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_moderation_comments_watchlist_author_id', table_name='moderation_comments')
    op.drop_constraint('fk_moderation_comments_watchlist_author_id', 'moderation_comments', type_='foreignkey')
    op.drop_column('moderation_comments', 'watchlist_author_id')
    
    op.drop_index('ix_watchlist_authors_status', table_name='watchlist_authors')
    op.drop_index('ix_watchlist_authors_settings_id', table_name='watchlist_authors')
    op.drop_table('watchlist_authors')
    op.drop_table('watchlist_settings')
    # ### end Alembic commands ###
