DEFAULT_PAGE_SIZE = 1000
MAX_FRIENDS_LIMIT = 5000
MAX_UIDS_PER_REQUEST = 100

OK_USERS_GET_INFO_FIELDS = [
    "accessible", "age", "allowed_for_ads_vk", "allows_anonym_access",
    "allows_messaging_only_for_friends", "allow_add_to_friend", "badge",
    "become_vip_allowed", "bio", "birthday", "blocked", "blocks",
    "block_on_demand", "bookmarked", "business", "can_use_referral_invite",
    "can_vcall", "can_vmail", "city_of_birth", "close_comments_allowed",
    "common_friends_count", "current_location", "current_status",
    "current_status_date", "current_status_date_ms", "current_status_id",
    "current_status_mood", "current_status_track_id", "dzen_token", "email",
    "executor", "external_share_link", "first_name",
    "first_name_instrumental", "followers_count", "forbids_mentioning",
    "friend", "friends_count", "friend_invitation", "friend_invite_allowed",
    "gender", "group_invite_allowed", "has_daily_photo", "has_email",
    "has_groups_to_comment", "has_moderating_groups", "has_phone",
    "has_pinned_feed", "has_products", "has_service_invisible",
    "hobby_expert", "hobby_topic", "internal_pic_allow_empty",
    "invited_by_friend", "is_merchant", "last_name",
    "last_name_instrumental", "last_online", "last_online_ms", "locale",
    "location", "location_of_birth", "modified_ms", "name",
    "name_instrumental", "new_user", "nn_photo_set_ids", "odkl_block_reason",
    "odkl_email", "odkl_login", "odkl_mobile", "odkl_mobile_activation_date",
    "odkl_mobile_status", "odkl_user_options", "odkl_user_status",
    "odkl_voting", "online", "partner_link_create_allowed", "photo_id",
    "pic1024x768", "pic128max", "pic128x128", "pic180min", "pic190x190",
    "pic224x224", "pic240min", "pic288x288", "pic320min", "pic50x50",
    "pic600x600", "pic640x480", "picgif", "picmp4", "picwebm", "pic_1",
    "pic_2", "pic_3", "pic_4", "pic_5", "pic_base", "pic_full", "pic_max",
    "possible_relations", "premium", "presents", "private", "profile_buttons",
    "profile_cover", "profile_photo_suggest_allowed", "pymk_pic224x224",
    "pymk_pic288x288", "pymk_pic600x600", "pymk_pic_full", "ref",
    "registered_date", "registered_date_ms", "relations", "relationship",
    "returning", "rkn_mark", "send_message_allowed", "shortname", "show_lock",
    "skill", "status", "total_photos_count", "uid",
    "update_photos_with_me_checked_time", "url_chat", "url_chat_mobile",
    "url_profile", "url_profile_mobile", "vip", "vk_id",
]
