from typing import Protocol


class AuthorRepository(Protocol):
    async def list_authors(self, **filters) -> dict: ...
    async def get_author(self, vk_author_id: int) -> dict | None: ...
    async def list_authors_bulk(self, vk_author_ids: list[int]) -> list[dict]: ...
    async def update_verified_at(self, vk_author_id: int) -> bool: ...
    async def get_all_author_ids(self) -> list[int]: ...
    async def bulk_update_profiles(self, profiles: list[dict]) -> int: ...
    async def delete_author_and_comments(self, vk_author_id: int) -> None: ...


class GroupRepository(Protocol):
    async def list_groups(self, **filters) -> dict: ...
    async def get_group(self, vk_group_id: int) -> dict | None: ...
    async def search_groups(self, query: str, limit: int) -> dict: ...
    async def list_groups_bulk(self, vk_group_ids: list[int]) -> list[dict]: ...
    async def upsert_group(self, group: dict) -> None: ...
    async def delete_group_and_related(self, vk_group_id: int) -> None: ...


class PostRepository(Protocol):
    async def list_posts(self, page: int, limit: int) -> dict: ...
    async def get_post(self, external_key: str) -> dict | None: ...
    async def list_comments(self, page: int, limit: int) -> dict: ...
    async def list_posts_bulk(self, external_keys: list[str]) -> list[dict]: ...
