from datetime import datetime
from typing import Protocol


class MonitoringMessageRepository(Protocol):
    async def find_messages(
        self,
        *,
        keywords: list[str],
        limit: int,
        offset: int,
        from_date: datetime | None,
        sources: list[str] | None,
    ) -> list[dict]: ...

    async def find_distinct_chats(self) -> list[dict]: ...


class MonitoringGroupRepository(Protocol):
    async def list_groups(self, **filters) -> list[object]: ...
    async def count_groups(self, **filters) -> int: ...
    async def get_group(self, group_id: int) -> object | None: ...
    async def upsert_group(self, **values) -> object: ...
    async def update_group(self, group_id: int, **values) -> object | None: ...
    async def delete_group(self, group_id: int) -> bool: ...
