LISTING_FIELD_KEYS = {
    "url",
    "source",
    "externalId",
    "title",
    "description",
    "price",
    "currency",
    "address",
    "city",
    "latitude",
    "longitude",
    "rooms",
    "areaTotal",
    "areaLiving",
    "areaKitchen",
    "floor",
    "floorsTotal",
    "publishedAt",
    "contactName",
    "contactPhone",
    "images",
    "sourceAuthorName",
    "sourceAuthorPhone",
    "sourceAuthorUrl",
    "sourcePostedAt",
    "sourceParsedAt",
    "metadata",
}

STRING_FIELDS = {
    "source",
    "externalId",
    "title",
    "description",
    "currency",
    "address",
    "city",
    "contactName",
    "contactPhone",
    "sourceAuthorName",
    "sourceAuthorPhone",
    "sourceAuthorUrl",
    "sourcePostedAt",
}

NUMERIC_FIELDS = {
    "price",
    "latitude",
    "longitude",
    "rooms",
    "areaTotal",
    "areaLiving",
    "areaKitchen",
    "floor",
    "floorsTotal",
}

DATE_FIELDS = {"publishedAt", "sourceParsedAt"}

FIELD_TO_COLUMN = {
    "source": "source",
    "externalId": "external_id",
    "title": "title",
    "description": "description",
    "url": "url",
    "price": "price",
    "currency": "currency",
    "address": "address",
    "city": "city",
    "latitude": "latitude",
    "longitude": "longitude",
    "rooms": "rooms",
    "areaTotal": "area_total",
    "areaLiving": "area_living",
    "areaKitchen": "area_kitchen",
    "floor": "floor",
    "floorsTotal": "floors_total",
    "publishedAt": "published_at",
    "contactName": "contact_name",
    "contactPhone": "contact_phone",
    "images": "images",
    "sourceAuthorName": "source_author_name",
    "sourceAuthorPhone": "source_author_phone",
    "sourceAuthorUrl": "source_author_url",
    "sourcePostedAt": "source_posted_at",
    "sourceParsedAt": "source_parsed_at",
    "manualNote": "manual_note",
    "archived": "archived",
}

MANUAL_FIELDS = {
    "title", "description", "price", "currency",
    "address", "city", "contactName", "contactPhone",
}
