"""create monitoring_groups table

Revision ID: 9405ab574a54
Revises: 993558031ef5
Create Date: 2026-05-25 18:17:47.159969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9405ab574a54'
down_revision: Union[str, None] = '993558031ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_groups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('messenger', sa.String(length=32), nullable=False),
    sa.Column('chat_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('messenger', 'chat_id', name='uq_monitoring_groups_messenger_chat')
    )
    op.create_index('ix_monitoring_groups_category', 'monitoring_groups', ['category'], unique=False)
    op.create_index('ix_monitoring_groups_messenger', 'monitoring_groups', ['messenger'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_monitoring_groups_messenger', table_name='monitoring_groups')
    op.drop_index('ix_monitoring_groups_category', table_name='monitoring_groups')
    op.drop_table('monitoring_groups')
    # ### end Alembic commands ###
