"""add_verified_at_to_content_authors

Revision ID: 993558031ef5
Revises: 20260524_0002
Create Date: 2026-05-24 21:04:39.230216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '993558031ef5'
down_revision: Union[str, None] = '20260524_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_authors', sa.Column('verifiedAt', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_authors', 'verifiedAt')
    # ### end Alembic commands ###
