"""add_vk_friends_export_tables

Revision ID: 92827354899c
Revises: 20260508_0001
Create Date: 2026-05-25 09:58:05.156891

"""
<<<<<<< HEAD
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
=======
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
>>>>>>> 59c5b02f74109d896c970438b9ab9949727f89da
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92827354899c'
<<<<<<< HEAD
down_revision: Union[str, None] = '20260508_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
=======
down_revision: str | None = '20260508_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None
>>>>>>> 59c5b02f74109d896c970438b9ab9949727f89da


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vk_friends_export_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vk_user_id', sa.BigInteger(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('xlsx_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vk_friends_job_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['vk_friends_export_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vk_friends_job_logs_job_id', 'vk_friends_job_logs', ['job_id'], unique=False)
    op.create_table('vk_friends_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('vk_friend_id', sa.BigInteger(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['vk_friends_export_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vk_friends_records_job_id', 'vk_friends_records', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vk_friends_records_job_id', table_name='vk_friends_records')
    op.drop_table('vk_friends_records')
    op.drop_index('ix_vk_friends_job_logs_job_id', table_name='vk_friends_job_logs')
    op.drop_table('vk_friends_job_logs')
    op.drop_table('vk_friends_export_jobs')
    # ### end Alembic commands ###
